version: '3'

tasks:

  hello:
    desc: "Hello World from Task!"
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  compile-contracts:
    desc: "Compile the Solidity contracts"
    cmds:
      - npx hardhat compile
    silent: true

  reset:
    desc: "Reset the NodeJS Hardhat environment"
    cmds:
      - npm run reset
    silent: true

  test:
    desc: "Run the development tests using a temporary Hardhat node"
    cmds:
      - npx hardhat test
    silent: true

  show-example-script-commands:
    desc: "Show the example script commands"
    cmds:
      - cat example-script-commands.txt
    silent: true

  start-local-node:
    desc: "Start a local Hardhat node"
    cmds:
      - npx hardhat node
    silent: true

  deploy-to-local:
    desc: "Deploy the HelloWorld contract to a Hardhat node running locally"
    cmds:
      - npx hardhat run scripts/deploy.js --network local
    silent: true

  deploy-to-testnet:
    desc: "Deploy the HelloWorld contract to the Sepolia testnet"
    cmds:
      - npx hardhat run scripts/deploy.js --network sepolia
    silent: true
    prompt: This command will spend testnet Ethereum (SepoliaETH) - Do you want to continue?

  deploy-to-mainnet:
    desc: "Deploy the HelloWorld contract to the Ethereum mainnet"
    cmds:
      - npx hardhat run scripts/deploy.js --network mainnet
    silent: true
    prompt: This command will spend Ethereum (ETH) - Do you want to continue?
